engine: "knitr"
format:
    revealjs:
      theme: [default, custom.scss]
      show-slide-number: all
      footer: "Penalized Regression | LASSO and Ridge"
      transition: slide
      background-transition: fade
      slide-number: true
      scrollable: true
      chalkboard: true
      preview-links: auto
      fig-width: 8
      fig-height: 6
      controls-layout: bottom-right
      controls-tutorial: true
